steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/canvas-joy-456715-b1/bikeshare-pipeline-image', '.']

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/canvas-joy-456715-b1/bikeshare-pipeline-image']




  # Step 3: Run the job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - bikeshare-pipeline-job
      - --region=us-east1

images:
  - 'gcr.io/canvas-joy-456715-b1/bikeshare-pipeline-image'


options:
  logging: CLOUD_LOGGING_ONLY



